> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy Functions


The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [5]:
import jovian

In [6]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115009/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115009/numpy-array-operations


'https://jovian.com/2115009/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [8]:
# List of functions explained 
function1 = np.concatenate
function2 = np.sum
function3 = np.max
function4 = np.transpose
function5 = np.mean

## Function 1 - np.concatenate 

Performs the conacatenate operation between two numpy arrays

In [23]:
# Example 1 - 
arr1 = [[1, 2], [3, 4]]
arr2 = [[5, 6], [8, 9]]

np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 8, 9]])

Here the array1 and array2 input is given and we are performing the concatenate operation for these two arrays.The axis is set to 1 so that it will bw concatenated from the first list.

In [26]:
#Example 2
arr1=np.array([[5,6],[2,3]])
arr2=np.array([[1,2],[7,8.0]])
np.concatenate((arr1,arr2),axis=1)

array([[5., 6., 1., 2.],
       [2., 3., 7., 8.]])

 The array1 and array2 input is defined but a single digit is given as floating point value so all the output values will be displayed as floating point values.

In [33]:
# Example 3 
arr1 = [[1, 2], 
        [3, 4]]

arr2 = [[5, 6,7], 
        [8, 9,10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

Both arrays are of different size but gives the output.

In [34]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115009/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115009/numpy-array-operations


'https://jovian.com/2115009/numpy-array-operations'

## Function 2 - np.sum
Returns the sum 

In [36]:
# Example 1 
arr1=np.array([3,4])
arr1.sum()

7

The above example is calculating the sum of a single dimensional array.

In [39]:
# Example 2 
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
np.sum((arr1,arr2),axis=1)

array([[4, 6],
       [4, 6]])

The above example is calculating the sum of a two dimensional array.

In [40]:
# Example 3
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[8,9],[7,5],[4,2]])
np.sum(arr1*arr2)

99

The above example is calculating the whole sum of two arrays by performing matrix multiplication.

In [41]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "2115009/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/2115009/numpy-array-operations


'https://jovian.com/2115009/numpy-array-operations'

## Function 3 - np.max

Returns the highest value

In [11]:
# Example 1 
arr1=np.array([1,2,3,7])
np.max(arr1)

7

Here among all the numbers in the array the highest value 7 is printed as output.

In [18]:
# Example 2 
arr1=np.array([[3,4],[5,6]])
arr2=np.array([[2,3],[7,8]])
np.max(arr1*arr2)

48

we have multiplied the two arrays and printed the maximum among those numbers.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - Transpose

Gives the transpose of the array


In [2]:
# Example 1
arr1=np.array([[1,2],[3,4]])
np.transpose(arr1)

array([[1, 3],
       [2, 4]])

the transpose of a simple matrix

In [4]:
# Example 2 
arr1=np.array([1,2])
arr2=np.array([3,4])
np.transpose(arr1*arr2)

array([3, 8])

Multiplying two simple arrays and then print the transpose of the resultant array

In [10]:
arr1=([1,2,3],[4,5,6])
arr2=([7,8,9],[10,11,12])
np.transpose(arr1+arr2)


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

Adding two arrays and then print the transpose as result

Some closing comments about when to use this function.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - np.mean



In [19]:
# Example 1
arr1=np.array([10,20,30,40])
np.mean(arr1)

25.0

Gives the mean value for the above array

In [22]:
# Example 2
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.mean(arr1*arr2)

17.5

Multiplied the two arrays and then find the mean 

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>