Numpy functions


1.To display a array

In [4]:
import numpy as np

In [6]:
array1=[1,2,3]

In [7]:
array1

[1, 2, 3]

In [8]:
array2=np.array([1,2,3])

In [9]:
array2

array([1, 2, 3])

The first example is displaying a normal array and the second one is displaying a numpy array

2.To display a list

In [1]:
arr=[[1,2,3],[4,5,6],[7,8,9]]

In [2]:
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The first example is displaying a normal list and the second one is displaying a numpy list

3.arange

The arange function displays a list of values within a given range of values

Syntax: arange(lower limit,upper limit , increment(optional))

In [8]:
a=np.arange(1,10)

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b=np.arange(1,10,2)

In [12]:
b

array([1, 3, 5, 7, 9])

In [15]:
c=np.arange(100,500,100)

In [16]:
c

array([100, 200, 300, 400])

4. zeros
   
This function is used to create an array filled with zeros.

In [17]:
s=np.zeros(4)

In [18]:
s

array([0., 0., 0., 0.])

In [22]:
f=np.zeros((2,3))

In [23]:
f

array([[0., 0., 0.],
       [0., 0., 0.]])

np.zeros((2,3)) returns a matrix of shape (2,3) filled with zeros. 

It refers to 2 rows & 3 columns.


5.ones

This function is similar to zeros function but instead of zeros it is filled with ones.

In [24]:
e=np.ones(4)

In [25]:
e

array([1., 1., 1., 1.])

In [26]:
k=np.ones((4,2))

In [27]:
k

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

This returns a matrix of shape (4,2) filled with ones. 

It refers to 4 rows & 2 columns.

6.linspace

This function is used to create an array with a specified number of evenly spaced values

In [30]:
h=np.linspace(0,2,5)

In [31]:
h

array([0. , 0.5, 1. , 1.5, 2. ])

7.Indexing in array

In [32]:
a1=np.array([10,20,30,40,50])

In [33]:
a1[0]

10

In [35]:
a1[-1]

50

Negative indexing also works in numpy

8.full

In [36]:
d=np.full([2,3],5)

In [37]:
d

array([[5, 5, 5],
       [5, 5, 5]])

In this, the array is created with 2 rows and 3 columns and fills all the elements with 5

9. eye

   This function creates identity matrix with the specified number of rows an columns

In [41]:
m=np.eye(3,dtype='int')

In [42]:
m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

10.To find size of an array

In [43]:
l=np.array([2,3,7,8,1])

In [45]:
l.size

5